server:
  address: 0.0.0.0
  port: 8002
  compression:
    enabled: true
  http2:
    enabled: true

  ssl:
    enabled: true
    key-alias: santomcat
    key-store: classpath:ssl/server.p12
    key-store-type: PKCS12

    key-password: Zerkalo82
    key-store-password: Zerkalo82
    trust-store-password: changeit

  error:
    whitelabel:
      enabled: false

spring:
  rabbitmq:
    host: ${server.address}
    port: 5672
    username: guest
    password: guest
    ssl:
      enabled: true
      key-store: ${server.ssl.key-store}
      key-store-type: PKCS12
      key-store-password: ${server.ssl.key-password}
      trust-store-password: ${server.ssl.trust-store-password}
    virtual-host: /

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          r2dbc: DEBUG