server:
  address: 0.0.0.0
  port: 8002
  compression:
    enabled: true
  http2:
    enabled: true

  ssl:
    enabled: false
    key-alias: santomcat
    key-store: classpath:ssl/server.p12
    key-store-type: PKCS12

    key-password: Zerkalo82
    key-store-password: Zerkalo82
    trust-store-password: changeit

  error:
    whitelabel:
      enabled: false

spring:
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: guest
    password: guest

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data:
          r2dbc: DEBUG